### ISSUE TITLE
Port ros_msgs/point_cloud2.py to ROS2

### ISSUE THREAD

**Issue by dmorris0** [ros2/common_interfaces#127]
## Feature request

ros_msgs/point_cloud2.py from here: http://docs.ros.org/jade/api/sensor_msgs/html/point__cloud2_8py.html is not yet in ROS2.  

#### Feature description

This is needed to extract field information from subscribed PointCloud2 messages.  I think anyone wanting to subscribe to PointCloud2 messages with a Python ROS2 node will need this.

**Comment by hidmic** [comment]
@dmorris0 that's a good idea. 

Would you be willing to contribute it?

**Comment by dmorris0** [comment]
Actually, this is being addressed here: https://github.com/ros2/common_interfaces/pull/128

**Comment by dmorris0** [comment]
This is addressed here: https://github.com/ros2/common_interfaces/pull/128
