### ISSUE TITLE
`script-dir` and `install-scripts` will not be supported in future versions

### ISSUE THREAD

**Issue by eduidl** [ros2/common_interfaces#147]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - from source
- Version or commit hash:
  - 7597e72797e33859b365d90be7a20d9e66813b95
- DDS implementation:
  - N/A
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

```
$ colcon build
```

#### Expected behavior

No warnings

#### Actual behavior

Following warnings

```
/usr/local/lib/python3.8/dist-packages/setuptools/dist.py:634: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/setuptools/dist.py:634: UserWarning: Usage of dash-separated 'install-scripts' will not be supported in future versions. Please use the underscore name 'install_scripts' instead
  warnings.warn(
```

#### Additional information

https://github.com/ros2/common_interfaces/blob/7597e72797e33859b365d90be7a20d9e66813b95/sensor_msgs_py/setup.cfg#L1-L4

**Comment by clalancette** [comment]
This one was fixed, so closing this.
