### ISSUE TITLE
New release into foxy

### ISSUE THREAD

**Issue by mintar** [ros2/common_interfaces#168]
Could you please create a new release into foxy to get #164 released? I have a pull request for `vision_opencv` that depends on it.

**Comment by gbiggs** [comment]
Sorry for the delay getting this done. I'm waiting on permissions for the release repository.

**Comment by hidmic** [comment]
Oof, thanks for picking this up @gbiggs. My apologies.

**Comment by gbiggs** [comment]
@mintar I've done the release (I hope). It should be in the next sync.
