### ISSUE TITLE
status field in NavSatStatus message has bad default value

### ISSUE THREAD

**Issue by jasonbeach** [ros2/common_interfaces#196]
## Bug report
When the NavSatStatus.msg is default constructed, status = 0 which by definition is an unaugmented fix as opposed to NO_FIX (or even better something like UNKNOWN)

#### Expected behavior
I would expect the status field in a default constructed NavSatStatus message to be either NO_FIX or something other than something indicating the fix was valid.  

#### Actual behavior
If you Default construct the NavSatFix / NavSatStatus message, the status field will indicate a valid fix (0);

the service field also is a little weird in that it's default value (0) is not defined. (There should be a uint16 SERVICE_UNKNOWN = 0)

**Comment by Ryanf55** [comment]
Could this be targeted for Iron?
