### ISSUE TITLE
Release for Humble 

### ISSUE THREAD

**Issue by mrkbac** [ros2/common_interfaces#213]
Hey, is it possible the create a new release for Humble before the next sync?

Sadly #211 was not included in the last sync.

**Comment by audrow** [comment]
I've released this for Humble here: https://github.com/ros/rosdistro/pull/35793.

I'll be announcing an upcoming patch release in the next day or so.

**Comment by audrow** [comment]
The sync and patch are out! https://discourse.ros.org/t/new-packages-and-patch-release-for-humble-hawksbill-2023-01-27/29469

Sorry for the delay. There were a lot of unexpected regressions to work through.
