### ISSUE TITLE
Uncommenting Messages

### ISSUE THREAD

**Issue by geoffviola** [ros2/common_interfaces#22]
When will more messages be uncommented? It would be nice if the following specific messages were uncommented in the next release:
geometry_msgs/Pose2D
geometry_msgs/PoseArray
nav_msgs/MapMetaData
nav_msgs/OccupancyGrid
nav_msgs/Path

**Comment by dhood** [comment]
Hi @geoffviola, we have enabled all messages in https://github.com/ros2/common_interfaces/pull/23 so they will now be included in pre-built binaries by default.
Thank you for the suggestion
