### ISSUE TITLE
Adding unique identifer field to Polygon/Polygon Stamped

### ISSUE THREAD

**Issue by SteveMacenski** [ros2/common_interfaces#230]
As part of https://github.com/ros-planning/navigation2/pull/3885, we're interested in representing footprints as polygons and storing them to do collision monitoring with respect to for multi-robot fleets.

Managing the `N` polygons and new incoming messages is complicated by the fact that the standard Polygon message has no form of unique ID field (int, uuid, etc) to identify one physical object instance being represented at `t=T`.

I would like to propose adding to PolygonStamped and potentially Polygon a `uint16 id` field as http://docs.ros.org/en/noetic/api/visualization_msgs/html/msg/Marker.html and others have themselves for similar deconfliction of unique objects.

**Comment by SteveMacenski** [comment]
It would look like

```
# This represents a Polygon with reference coordinate frame and timestamp

std_msgs/Header header
Polygon polygon
uint16 id
```

Which would add minimal overhead to the message definitions and not change any existing fields' name or type, so it should not break anyone's current use-cases

**Comment by SteveMacenski** [comment]
@clalancette who's the right person to ping about this?

**Comment by SteveMacenski** [comment]
https://github.com/ros2/common_interfaces/pull/232 implements

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2023-11-16/34757/1
