### ISSUE TITLE
colcon build error

### ISSUE THREAD

**Issue by WeiHoongAries** [ros2/common_interfaces#234]
- Operating System:
Ubuntu 22.04
- Installation type:
Source
- Version or commit hash:
  Humble

#### Steps to reproduce issue
I tried to build a custom interface in between two nodes following this [tutorial](https://docs.ros.org/en/crystal/Tutorials/Custom-ROS2-Interfaces.html). however, i experience some errors while colcon build the interface

##  CMakeLists.txt
cmake_minimum_required(VERSION 3.8)
project(custom_interfaces)

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

find_package(ament_cmake REQUIRED)
find_package(rosidl_default_generators REQUIRED)

rosidl_generate_interfaces(${PROJECT_NAME}
  "msg/DetectedObject.msg"
)

if(BUILD_TESTING)
  find_package(ament_lint_auto REQUIRED)
  set(ament_cmake_copyright_FOUND TRUE)
  set(ament_cmake_cpplint_FOUND TRUE)
  ament_lint_auto_find_test_dependencies()
endif()

ament_export_dependencies(rosidl_default_runtime)

ament_package()

DetectedObject.msg
Header header
string class_name
float32 confidence

## package.xml
<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>custom_interfaces</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="wwl@todo.todo">wwl</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <buildtool_depend>rosidl_default_generators</buildtool_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>
  
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

#### Actual behavior

Starting >>> custom_interfaces
 stderr: custom_interfaces                             
In file included from /home/wwl/test_ws/build/custom_interfaces/rosidl_generator_c/custom_interfaces/msg/detail/detected_object__functions.h:19,
                 from /home/wwl/test_ws/build/custom_interfaces/rosidl_generator_c/custom_interfaces/msg/detail/detected_object__functions.c:4:
/home/wwl/test_ws/build/custom_interfaces/rosidl_generator_c/custom_interfaces/msg/detail/detected_object__struct.h:22:10: fatal error: custom_interfaces/msg/detail/header__struct.h: No such file or directory
   22 | #include "custom_interfaces/msg/detail/header__struct.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/custom_interfaces__rosidl_generator_c.dir/build.make:105: CMakeFiles/custom_interfaces__rosidl_generator_c.dir/rosidl_generator_c/custom_interfaces/msg/detail/detected_object__functions.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:213: CMakeFiles/custom_interfaces__rosidl_generator_c.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
In file included from /home/wwl/test_ws/build/custom_interfaces/rosidl_typesupport_cpp/custom_interfaces/msg/detected_object__type_support.cpp:7:
/home/wwl/test_ws/build/custom_interfaces/rosidl_generator_cpp/custom_interfaces/msg/detail/detected_object__struct.hpp:20:10: fatal error: custom_interfaces/msg/detail/header__struct.hpp: No such file or directory
   20 | #include "custom_interfaces/msg/detail/header__struct.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/wwl/test_ws/build/custom_interfaces/rosidl_typesupport_fastrtps_cpp/custom_interfaces/msg/detail/detected_object__rosidl_typesupport_fastrtps_cpp.hpp:11,
                 from /home/wwl/test_ws/build/custom_interfaces/rosidl_typesupport_fastrtps_cpp/custom_interfaces/msg/detail/dds_fastrtps/detected_object__type_support.cpp:4:
/home/wwl/test_ws/build/custom_interfaces/rosidl_generator_cpp/custom_interfaces/msg/detail/detected_object__struct.hpp:20:10: fatal error: custom_interfaces/msg/detail/header__struct.hpp: No such file or directory
   20 | #include "custom_interfaces/msg/detail/header__struct.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
compilation terminated.
gmake[2]: *** [CMakeFiles/custom_interfaces__rosidl_typesupport_cpp.dir/build.make:86: CMakeFiles/custom_interfaces__rosidl_typesupport_cpp.dir/rosidl_typesupport_cpp/custom_interfaces/msg/detected_object__type_support.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:395: CMakeFiles/custom_interfaces__rosidl_typesupport_cpp.dir/all] Error 2
gmake[2]: *** [CMakeFiles/custom_interfaces__rosidl_typesupport_fastrtps_cpp.dir/build.make:91: CMakeFiles/custom_interfaces__rosidl_typesupport_fastrtps_cpp.dir/rosidl_typesupport_fastrtps_cpp/custom_interfaces/msg/detail/dds_fastrtps/detected_object__type_support.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:343: CMakeFiles/custom_interfaces__rosidl_typesupport_fastrtps_cpp.dir/all] Error 2
In file included from /home/wwl/test_ws/build/custom_interfaces/rosidl_typesupport_introspection_cpp/custom_interfaces/msg/detail/detected_object__type_support.cpp:12:
/home/wwl/test_ws/build/custom_interfaces/rosidl_generator_cpp/custom_interfaces/msg/detail/detected_object__struct.hpp:20:10: fatal error: custom_interfaces/msg/detail/header__struct.hpp: No such file or directory
   20 | #include "custom_interfaces/msg/detail/header__struct.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/custom_interfaces__rosidl_typesupport_introspection_cpp.dir/build.make:91: CMakeFiles/custom_interfaces__rosidl_typesupport_introspection_cpp.dir/rosidl_typesupport_introspection_cpp/custom_interfaces/msg/detail/detected_object__type_support.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:369: CMakeFiles/custom_interfaces__rosidl_typesupport_introspection_cpp.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2

Failed   <<< custom_interfaces [3.22s, exited with code 2]

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
