### ISSUE TITLE
Add copyright notice to LICENSE files

### ISSUE THREAD

**Issue by evan-flynn-apexai** [ros2/common_interfaces#239]
Would it be possible to add what the copyright notice should state for this repos license files?
For both the top-level LICENSE file and any other LICENSE file inside the repo?

**Comment by clalancette** [comment]
That should be there already in https://github.com/ros2/common_interfaces/blob/rolling/CONTRIBUTING.md .  Or do you mean something else?

**Comment by evan-flynn-apexai** [comment]
@clalancette the `sensor_msgs_py` package has [its own license file](https://github.com/ros2/common_interfaces/tree/rolling/sensor_msgs_py)...which is different than the top-level Apache 2 license.

So I think it needs its own copyright notice, right?
