### ISSUE TITLE
Re-enable copyright linting in sensor_msgs

### ISSUE THREAD

**Issue by clalancette** [ros2/common_interfaces#35]
Now that ament/ament_lint#73 has been merged, we should be able to re-enable copyright linting in the sensor_msgs package.  It is probably just a one line change.

**Comment by dirk-thomas** [comment]
Please create a PR for this change which just needs to remove [these two lines](https://github.com/ros2/common_interfaces/blob/96a6be9ee65f27605af24fe3b3a172697534c78a/sensor_msgs/CMakeLists.txt#L61-L62).
