### ISSUE TITLE
Printing the entire message as String

### ISSUE THREAD

**Issue by anasarrak** [ros2/common_interfaces#69]
Is there any way to print the entire message as String as ROS does with stringstream?
Example:

```
std_msgs::msg::String msg;
std::stringstream ss;
ss << msg;
RCLCPP_INFO(node->get_logger(), "%s\n",ss.str().c_str());
```

**Comment by dirk-thomas** [comment]
Atm there are no streaming operator defined for message. There is a ticket to add various to-string functions though: ros2/rosidl#259

Therefore I will close this ticket as a duplicate.
