### ISSUE TITLE
Request for more std_srvs to match std_msgs

### ISSUE THREAD

**Issue by peterpolidoro** [ros2/common_interfaces#73]
#### Feature description
Does it make sense to fill out the set of std_srvs to match the set of std_msgs? For example, there is a SetBool.srv now that takes a bool and returns a bool success and string message, it would be nice to also have a SetFloat64.srv that takes a float64 and returns a bool success and string message. 

#### Implementation considerations
This would be easy to implement, just copying the pattern of the SetBool.srv, with a matching srv file for each msg in std_msgs or at least some or most of them. I am happy to add these and submit a pull request if others think this is appropriate.

**Comment by dirk-thomas** [comment]
Please see the conversations on past ticket with similar requests: ros/common_msgs#21, ros/common_msgs#49, ros/std_msgs#7.

For all those cases we don't think adding more standard interface files with no semantic meaning is beneficial. Instead you should create a service with has specific semantic meaning for your use case, e.g. `SetDistanceThreshold` if you want to set a single integer.
