### ISSUE TITLE
Including moveit_msgs

### ISSUE THREAD

**Issue by tobi-v** [ros2/common_interfaces#77]
#### Feature description

Hello there! Is it possible to include the moveit_msgs as an interface in the next release?

**Comment by clalancette** [comment]
moveit_msgs is provided by the third-party https://github.com/ros-planning/moveit_msgs , not by the core of ROS 2 itself.  There has been some work ongoing to port moveit to ROS 2, but the port isn't yet complete: https://moveit.ros.org/moveit!/ros/2019/03/01/announcing-the-moveit-2-port.html .  I'll suggest you open an issue on the moveit_msgs repository above, as you may get a more definitive answer when that might be possible.  I'll close this for now, thanks for your interest.
