### ISSUE TITLE
Using sensor_msgs for control?

### ISSUE THREAD

**Issue by peterpolidoro** [ros2/common_interfaces#80]
I assume, based on the name, that there is a convention of only using sensor_msgs for feedback from sensors.

There are times, though, when it would be nice to set a sensor value as a goal or target to use for control. Would it be considered bad form to use a sensor_msg for a control topic? There would be a name mismatch, but it might be nice to have the goal data in exactly the same form as the feedback data.

Using control_msgs for control topics would be a better fit, but as control_msgs and sensor_msgs are in separate repositories, they seem to diverge in places in the latest releases or at least have that potential.

Would it be better to just use a sensor_msg for a control topic and not worry about the name mismatch or would it be better to work with the maintainers of the control_msgs repository to make sure it more closely follows sensor_msgs? Or could it make sense to add a message category to common_interfaces that mirrors sensor_msgs but is used for goal or target topics rather than feedback topics?

**Comment by dirk-thomas** [comment]
Closing duplicate post: https://answers.ros.org/question/341369/using-sensor_msgs-for-control/
