### ISSUE TITLE
Progress to Quality Level 1

### ISSUE THREAD

**Issue by brawner** [ros2/common_interfaces#84]
This issue tracks the progression of packages in `common_interfaces` that have been deemed necessary for Quality Level 1 and a 1.0 version level. It follows the outline described in [REP 2004](https://github.com/ros-infrastructure/rep/blob/c2ba03bac23b8f313e47820833fad000dbbe058b/rep-2004.rst). 

The packages slated for Quality Level 1 for ROS 2 Foxy are:
- diagnostic_msgs
- geometry_msgs
- nav_msgs
- sensor_msgs
- shape_msgs
- std_msgs
- stero_msgs
- trajectory_msgs
- visualization_msgs

Excluded for Quality Level 1 at this time:
- actionlib_msgs (set for deprecation)
- common_interfaces

# Progress common to all packages:
* [x] Version Policy
    - Follows ROS Core Quality Declaration
* [x] Version >= 1.0.0
* [x] Change Control Process
    - Follows ROS Core
* [x] No testing required because these packages just define messages and services 

Documentation
* [x] Declared set of licenses
* [x] Copyright statement in each source file
    - Copyright statements aren't needed in msg/srv files

Dependencies:
* [x] non-ROS dependencies are equivalent level 1

Platform Support
* [x] Supports all tier 1 platforms

# Progress of specific packages
## diagnostic_msgs
Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API. 
* [x] Quality Declaration document

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - rosidl_default_runtime
    - builtin_interfaces
    - unique_identifier_msgs
* [x] non-ROS dependencies are equivalent level 1

## geometry_msgs
Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API. 
* [x] Quality Declaration document

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - rosidl_default_runtime
    - std_msgs
* [x] non-ROS dependencies are equivalent level 1

## nav_msgs
Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API. 
* [x] Quality Declaration document

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - rosidl_default_runtime
    - builtin_interfaces
    - geometry_msgs
    - std_msgs
* [x] non-ROS dependencies are equivalent level 1

## sensor_msgs
Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API. 
* [x] Quality Declaration document

Testing:
- Missing tests for distortion_models.hpp, fill_image.hpp, point_field_conversion.hpp

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - rosidl_default_runtime
    - builtin_interfaces
    - geometry_msgs
    - std_msgs
* [x] non-ROS dependencies are equivalent level 1

## shape_msgs
Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API. 
* [x] Quality Declaration document

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - rosidl_default_runtime
    - geometry_msgs
* [x] non-ROS dependencies are equivalent level 1

## std_msgs
Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API. 
* [x] Quality Declaration document

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - rosidl_default_runtime
    - builtin_interfaces
* [x] non-ROS dependencies are equivalent level 1

## std_srvs
Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API. 
* [x] Quality Declaration document

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - rosidl_default_runtime
* [x] non-ROS dependencies are equivalent level 1

## stereo_msgs
Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API. 
* [x] Quality Declaration document

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - rosidl_default_runtime
    - std_msgs
    - sensor_msgs
* [x] non-ROS dependencies are equivalent level 1

## trajectory_msgs
Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API. 
* [x] Quality Declaration document

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - rosidl_default_runtime
    - std_msgs
    - geometry_msgs
    - builtin_interfaces
* [x] non-ROS dependencies are equivalent level 1

## visualization_msgs
Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API. 
* [x] Quality Declaration document

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - rosidl_default_runtime
    - std_msgs
    - geometry_msgs
    - builtin_interfaces
* [x] non-ROS dependencies are equivalent level 1

**Comment by chapulina** [comment]
All packages reached level 1: https://github.com/ros2/common_interfaces/pull/135
