### ISSUE TITLE
Move example messages out of std_msgs

### ISSUE THREAD

**Issue by tfoote** [ros2/common_interfaces#89]
This is a follow up to the [Aggregate Foxy Message API Review](https://github.com/ros2/common_interfaces/pull/86)

Followup to: https://github.com/ros2/common_interfaces/pull/86/files#r392505128

We should look at moving any of the messages that are not actually standard to something more like `example_msgs` this will set expectations more clearly. 

This could have wide ranging effects and it might be worth adding explicit warnings into the generators to help with the migration process.

**Comment by tfoote** [comment]
Done in a combination of #116 and https://github.com/ros2/example_interfaces/pull/11

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/soss-a-whole-new-approach-to-your-ros-1-ros-2-bridge/17040/18

**Comment by delihus** [comment]
It was moved here https://github.com/ros2/example_interfaces/tree/jazzy/msg
